### ISSUE TITLE
Usage with Telescope

### ISSUE THREAD

**Issue by malles** [michaeldyrynda/laravel-efficient-uuid#11]
When using [Telescope](https://laravel.com/docs/5.8/telescope) with this package, Telescope will not work, failing with a _String data, right truncated: 1406 Data too long for column 'batch_id' at row 1_ error. This is because the Telescope models do not cast their uuids to binaries, and are storing the string value in the database.

Best workaround seems to use the new feature [migration-customization](https://laravel.com/docs/5.8/telescope#migration-customization) (from [v1.0.11, jan 28th](https://github.com/laravel/telescope/issues/525)). By publishing the migration files and manually changing the type from `uuid` to `char(36)` in all cases, Telescope will work again.

```php
$table->char('uuid', 36);
```
Just a heads-up for others running into this issue.

**Comment by NexPB** [comment]
I had the same issue as you with packages using uuid in their migrations.
So I made a fork https://github.com/NexPB/laravel-efficient-uuid it won't override the default uuid() method but instead give you a new method for your migrations:
`$table->uuidEfficient('uuid');`

**Comment by drsdre** [comment]
@NexPB I agree with creating a new migration blueprint for efficient uuid's instead of overwriting the default one.

May I suggest you create a pull request for your patches. This is of course a non backward compatible change which would warrant a full version number upgrade.

**Comment by michaeldyrynda** [comment]
I've created a PR with these changes in #13 if you wanted to give that a whirl.
