### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by wells** [michaeldyrynda/laravel-efficient-uuid#2]
Hey @michaeldyrynda 

I would like to confirm that you have _no plans_ to add in service provider autoloading to the composer.json of this package. Such as...

```
"extra": {
        "laravel": {
            "providers": [
                "Dyrynda\\Database\\LaravelEfficientUuidServiceProvider"
            ]
        }
    }
```

My hope and desire is to conditionally load this package in my own package service provider. I want to give the developer using my packages the ability to decide if they use binary(16) storage or not.

Just need some peace of mind and all that.

**Comment by michaeldyrynda** [comment]
At this stage, I think I will add it to the [complementary package](https://github.com/michaeldyrynda/laravel-model-uuid) but not this one. You raise an interesting point, though.

I wonder if you can use the `dont-discover` extra key in your package's `composer.json` to prevent it from being loaded, though.

**Comment by michaeldyrynda** [comment]
Doesn't look like the `dont-discover` key will work, so I will leave it out in this package.

https://twitter.com/taylorotwell/status/902321430980898816
