### ISSUE TITLE
Changing column definition in migration fails with `Unknown column type "efficientuuid" requested`

### ISSUE THREAD

**Issue by rogatty** [michaeldyrynda/laravel-efficient-uuid#20]
I try to change the column definition in a migration:
```
$table->efficientUuid('uuid')->nullable(false)->change();
```

I get this error when running the migration:
>Unknown column type "efficientuuid" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

**Comment by rogatty** [comment]
It's enough to add this at the top of your migration:
```
Schema::registerCustomDoctrineType(
  Doctrine\DBAL\Types\BinaryType::class,
  'efficientuuid',
  Doctrine\DBAL\Types\Types::BINARY
);
```

Maybe it could be done automatically as a part of this package? If not, then a note in the documentation would be nice.

**Comment by michaeldyrynda** [comment]
I've just pushed some changes [here](https://github.com/michaeldyrynda/laravel-efficient-uuid/tree/feature/support-changing-efficient-uuid-columns) that should address this.

Are you able to give it a go and report back @rogatty ?

**Comment by ctf0** [comment]
@michaeldyrynda any chance to merge to master ?

**Comment by michaeldyrynda** [comment]
Are either @rogatty or @ctf0 able to confirm if the changes I made in 5fe16fb solve this issue?

**Comment by ctf0** [comment]
@michaeldyrynda just tested it 
- fixed `EfficientUuid` namespace
- added the cast & the migration update as above
- got the error
```
 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`' at line 1 (SQL: ALTER TABLE serials CHANGE id id BINARY(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`)
```

**Comment by rogatty** [comment]
Sorry @michaeldyrynda but I ended up using Ordered UUID. The change looks good to me but I won't be able to test it. I think the collation error mentioned by @ctf0 is unrelated.

**Comment by rogatty** [comment]
Ah, I forgot that I already commented in https://github.com/michaeldyrynda/laravel-efficient-uuid/pull/21 – the migration works just fine.
