### ISSUE TITLE
how to generate a new Uuid using efficientUuid()

### ISSUE THREAD

**Issue by jcherrabi** [michaeldyrynda/laravel-efficient-uuid#25]
Hello there,
it is unclear to me on how to generate a new uuid for my test unit, can you please share an example?

       factory(App\User::class)->create([
            'id' => 1,
            'name' => 'Admin',
            'uuid' => efficientUuid('uuid'),
        ]);

gives an error???
thank you .

**Comment by michaeldyrynda** [comment]
You should be able to just set a valid UUID as a string, and the package will handle casting it properly if it's already set.

**Comment by michaeldyrynda** [comment]
I've added some extra handling and some tests around this, but essentially what you're after is:

```php
factory(App\User::class)->create([
    'id' => 1,
    'name' => 'Admin',
    'uuid' => $this->faker->uuid,
]);
```

The `EfficientUuid` cast will handle the rest for you.
