### ISSUE TITLE
how to use efficientUuid inside a $factory 

### ISSUE THREAD

**Issue by jcherrabi** [michaeldyrynda/laravel-efficient-uuid#27]
Hello guys,
i'm not sure how to use efficientUuid inside a factory to generate a new uuid for db testing, i always get call to undefined function efficientUuid ()
` <?php

use Dyrynda\Database\Casts\EfficientUuid;
use Faker\Generator as Faker;

$factory->define(App\Partner::class, function (Faker $faker) {
    return [
        'name'         => $faker->company,
        'email'        => $faker->companyEmail,
        'uuid'         => efficientUuid(),
        'created_at'   => now(),
        'updated_at'   => now(),
    ];
}); `
any sample code would be appreciated..
thank you

**Comment by michaeldyrynda** [comment]
You should be able to just use `$faker->uuid`, the custom casting will take care of the rest for you.
