### ISSUE TITLE
Custom resolveRouteBinding method

### ISSUE THREAD

**Issue by maxcelos** [michaeldyrynda/laravel-efficient-uuid#31]
Hi!

Can we have an optional custom resolveRouteBinding method on GeneratesUuid trait?

Would be nice to easily use route binding to models in controllers.

Here is a simple code example:

```
class Post extends Model
{
    use GeneratesUuid;

    // Default model binding behavior without this attribute or if it is false
    protected $bindUuid = true;
    ...
```

```
trait GeneratesUuid
{

    public function resolveRouteBinding($value, $field = null)
    {
        if (isset($this->bindUuid) && $this->bindUuid === true)
            return $this->whereUuid($value)->first();
        else
            return parent::resolveRouteBinding($value, $field);
    }
```

**Comment by alecgarcia** [comment]
I was literally just thinking about this on my way to work this morning. I think this would be a great addition!

**Comment by maxcelos** [comment]
Wrong repository!

I'll send a PR on michaeldyrynda/laravel-model-uuid
