### ISSUE TITLE
Validation error when checking if model exists using UUID

### ISSUE THREAD

**Issue by Teath** [michaeldyrynda/laravel-efficient-uuid#4]
I encountered an issue with validating form fields with UUIDs.

When validating if a value exists in the UUID column using the standard method,
`public function rules()
    {
        return [
            'model_uuid' => 'exists:models,uuid'
        ];
    }`

or performing a check using

`$model->where('uuid', $uuid)->exists()`

the result is false, even if the value actually exists, due to the difference between binary and string representation. The string uuid value is not automatically converted to the binary representation when performing the check.

I had to work around this by creating a custom rule, which uses the `Uuid::import()` method provided by the `webpatser/laravel-uuid` package:

```
use Illuminate\Contracts\Validation\Rule;
use Illuminate\Support\Facades\DB;
use Webpatser\Uuid\Uuid;

class ExistsUuid implements Rule
{

    private $table;

    /**
     * Create a new rule instance.
     *
     * @param $table
     */
    public function __construct($table)
    {
        $this->table = $table;
    }

    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        return DB::table($this->table)->where('uuid',  Uuid::import($value)->bytes)->exists();
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'This :attribute does not exist!';
    }
}
```

Used in a validator
`'model_uuid' => [new ExistsUuid('models')]`

I have two (three?) questions:

1. Is there a better workaround or built-in method to achieve this?
2. If not, can it be implemented?
3. If not, I think this should be mentioned in the readme.

Thanks!

**Comment by michaeldyrynda** [comment]
The [`whereUuid`](
https://github.com/michaeldyrynda/laravel-model-uuid/blob/76d7dd98199b0305ab9a6e085b5962382f16f756/src/GeneratesUuid.php#L114) scope that is part of the `laravel-model-uuid` package already handles the translation for you, you just need to provide your own custom rule to do the check. 

You can do this using a custom rule closure or rule object if you need to use the rule in multiple places 
https://laravel.com/docs/5.7/validation#custom-validation-rules
