### ISSUE TITLE
uuid v4 vs ordered (v6)

### ISSUE THREAD

**Issue by JosuelRocha** [michaeldyrynda/laravel-efficient-uuid#42]
I have a question and I would like to know your opinion.

I have a model with id as the primary key and uuid as the secondary key (I use unique instead of index), noting that all my external calls, that is, calls via API, I use uuid to identify the record, so I wonder, is it more efficient to use standard version 4 or version 6 (ordered)? Because I imagine the following, despite the uuid column being indexed, when making a request via API using uuid as an identifier, the database still needs to look for it in the index records, it would not be easier for the database to find this record if were "ordered"?

DB: MySQL/MariaDB

**Comment by michaeldyrynda** [comment]
I'm typically using the v6 UUIDs by default in most of my apps to aide in lookup. Given they're indexed anyway, I suspect it'll be a long while (millions on millions of records) before you'd feel any issues looking up individual records anyway.

I've not done any profiling on this to say for sure.
