### ISSUE TITLE
SQLite Support

### ISSUE THREAD

**Issue by stelgenhof** [michaeldyrynda/laravel-efficient-uuid#5]
Not so much of an issue, more of a question.

Since I use more often SQLite than MySQL, I am using currently Spatie's package for UUID's as it supports SQLite. I had a look at your package and can perhaps help you with adding support for SQLite.

One quick question I have is regarding the LaravelEfficientUuidServiceProvider. At the moment it is tightly couple to MySQL and if SQLite would be added, how do you think having different options available should work? Would it be an approach that this package provides a configuration so users can set with DB backend they are using?

What are your thoughts?

Cheers! Sacha

**Comment by michaeldyrynda** [comment]
Happy to review a PR to add support other drivers.

When I created this package, I was using MySQL, so it was the only driver I needed an implementation for. 

I think I tried SQLite, but at the time it didn’t support storing binary UUID (or I didn’t have time to figure out the implementation).

**Comment by michaeldyrynda** [comment]
Happy to accept a PR to add this functionality, but I have no plans to implement it myself.
