### ISSUE TITLE
Default value for uuid column

### ISSUE THREAD

**Issue by maxcelos** [michaeldyrynda/laravel-efficient-uuid#50]
Looking for a way to make easy to insert data using a graphic interface like TablePlus or Workbench. 

I'm testing setup the default value for uuid column to auto generate the binary uuid so we can just leave it black like the id:

```php
$table->efficientUuid('uuid')->index()->default(\Illuminate\Support\Facades\DB::raw('(uuid_to_bin(uuid()))'));
```

Does anyone uses it or see any problem?

![Screen Shot 2021-12-29 at 08 07 01](https://user-images.githubusercontent.com/15364289/147656119-9316b359-5ad1-49e3-a379-2f7361f49de5.png)

**Comment by michaeldyrynda** [comment]
I’ve not done this myself (usually leave it without a default and let dyrynda/laravel-model-uuid handle setting the value), but so long as the binary implementation matches the one in `ramsey/uuid` and you configure matching UUID versions, I don’t see a theoretical issue with this working.
