### ISSUE TITLE
UUID not generated when using Eloquent Upsert

### ISSUE THREAD

**Issue by albertBuenaventura** [michaeldyrynda/laravel-efficient-uuid#54]
UUID is not being generated when using the Upsert. I'm trying to insert a data that is not yet existing on my table.
```
EloquentModel::upsert(
    [
        [
            'type' => 'all',
            'name' => "All"
        ]
    ],
    ['type']
)
```

I've tried to use the `DB` but I'm getting an error
```
{
    "error": {
    "message": {
        "message": "Array to string conversion",
        "file": "/app/vendor/laravel/framework/src/Illuminate/Support/Str.php@596"
    },
    "status_code": 500
    }
}
```

**Comment by michaeldyrynda** [comment]
A UUID won’t be generated for an `upsert` statement because this is carried out at the database level, not within Laravel. 

As a result, the `saving` event the package depends on to generate the UUID is never fired. 

That is to say, that the package doesn’t (and can’t) support generation of UUID values on `upsert` queries. 

You would need to generate these values yourself and pass them as arguments of the `upsert` query.

**Comment by albertBuenaventura** [comment]
Thank you for answering @michaeldyrynda 

> You would need to generate these values yourself and pass them as arguments of the upsert query.

Yes I did try this. However I'm getting the same error I got from using the `DB`
```
{
    "error": {
    "message": {
        "message": "Array to string conversion",
        "file": "/app/vendor/laravel/framework/src/Illuminate/Support/Str.php@596"
    },
    "status_code": 500
    }
}
```
Code
```
use Ramsey\Uuid\Uuid;
use Illuminate\Support\Arr;

EloquentModel::upsert([
    [
        'uuid' => Arr::wrap(Uuid::fromString(Str::lower(Uuid::uuid4()->toString()))->getBytes()), //generate binary uuid
        'name' => Str::ucfirst(DefaultTags::ALL()),
        'type' => DefaultTags::ALL(),
    ],
], ['type']);
```

**Comment by michaeldyrynda** [comment]
You're passing an array (via `Arr::wrap()`) to the `uuid` column, which expects a string, hence the `Array to string conversion` error.

If you use `upsert`, I don't believe any part of this package will touch the query, so it should be sufficient to simply use `UUID::uuid4()->getBytes()`.

**Comment by albertBuenaventura** [comment]
That works! Thanks @michaeldyrynda
