### ISSUE TITLE
Laravel 11 compatibility 

### ISSUE THREAD

**Issue by suhui666** [michaeldyrynda/laravel-efficient-uuid#64]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dyrynda/laravel-efficient-uuid 5.0.0 requires illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-efficient-uuid[4.5.0, ..., 4.5.3] require illuminate/contracts ^8.12|^9.0 -> found illuminate/contracts[v8.12.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-efficient-uuid[4.3.0, ..., 4.4.0] require illuminate/container ^8.12 -> found illuminate/container[v8.12.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-efficient-uuid 4.2.0 requires php ^7.3 -> your php version (8.2.12) does not satisfy that requirement.
    - dyrynda/laravel-efficient-uuid[4.0.0, ..., 4.1.1] require php ^7.2.5 -> your php version (8.2.12) does not satisfy that requirement.
    - dyrynda/laravel-efficient-uuid[3.0.0, ..., 3.1.0] require php ^7.2 -> your php version (8.2.12) does not satisfy that requirement.
    - dyrynda/laravel-efficient-uuid 2.3.0 requires illuminate/container ~5.4 -> found illuminate/container[v5.4.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-efficient-uuid 2.2.0 requires illuminate/container 5.4.* || 5.5.* || 5.6.* || 5.7.* -> found illuminate/container[v5.4.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-efficient-uuid 2.1.0 requires illuminate/container 5.4.* || 5.5.* || 5.6.* -> found illuminate/container[v5.4.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-efficient-uuid 2.0.0 requires illuminate/container 5.4.* || 5.5.* -> found illuminate/container[v5.4.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - dyrynda/laravel-efficient-uuid 1.0.0 requires illuminate/container 5.4.* -> found illuminate/container[v5.4.0, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires dyrynda/laravel-efficient-uuid * -> satisfiable by dyrynda/laravel-efficient-uuid[1.0.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 3.0.0, 3.0.1, 3.1.0, 4.0.0, ..., 4.5.3, 5.0.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require dyrynda/laravel-efficient-uuid:*" to figure out if any version is installable, or "composer require dyrynda/laravel-efficient-uuid:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by michaeldyrynda** [comment]
If you need Laravel 11 support, please swap to [dyrynda/laravel-model-uuid](https://github.com/michaeldyrynda/laravel-model-uuid).
