### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by stelgenhof** [michaeldyrynda/laravel-efficient-uuid#9]
Please add support for Laravel 5.8. I am trying to install this package when using Laravel 5.8, but fails since this package only supports up till 5.7.

Cheers! Sacha

**Comment by craigsansam** [comment]
I have an open pull request which adds 5.8 support - #7

**Comment by stelgenhof** [comment]
@craigsansam Must I have missed that! Thanks. Will close this issue then.
